FROM openjdk:17
WORKDIR /usr/src/central-service
COPY target/central-service-0.0.1-SNAPSHOT.jar /usr/src/central-service
CMD ["java", "-jar", "/usr/src/central-service/central-service-0.0.1-SNAPSHOT.jar"]