apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp
          image: 698790155454.dkr.ecr.us-east-1.amazonaws.com/myapp:latest
          resources:
            limits:
              memory: "1Gi"
              cpu: "500m"
          ports:
            - name: tcp
              containerPort: 8250
---
apiVersion: v1
kind: Service
metadata:
  name: myapp
spec:
  selector:
    app: myapp
  ports:
    - port: 8250
      targetPort: 8250
  type: LoadBalancer