apiVersion: apps/v1
kind: Deployment
metadata:
  name: central-service
spec:
  selector:
    matchLabels:
      app: central-service
  template:
    metadata:
      labels:
        app: central-service
    spec:
      containers:
        - name: central-service
          image: 052724743115.dkr.ecr.us-east-1.amazonaws.com/central:latest
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
          ports:
            - name: tcp
              containerPort: 8250
---
apiVersion: v1
kind: Service
metadata:
  name: central-service
spec:
  selector:
    app: central-service
  ports:
    - port: 8250
      targetPort: 8250
  type: LoadBalancer